version: "3.8"

services:
  interface:
    build: ./
    image: christophercautivar/dev-simple-todo-webapp
    ports:
      - 3000:3000
    working_dir: /app
    volumes:
      - ./:/app
  #   environment:
  #     MYSQL_HOST: mysql
  #     MYSQL_USER: root
  #     MYSQL_PASSWORD: secret
  #     MYSQL_DB: todos

  # mysql:
  #   image: mysql:5.7
  #   volumes:
  #     - todo-mysql-data